import clsx from 'clsx';
import type { Metadata } from 'next';
import { useLocale } from 'next-intl';
import { Inter } from 'next/font/google';
import { notFound } from 'next/navigation';
import { PropsWithChildren } from 'react';
import './globals.css';

const inter = Inter({ subsets: ['latin'] })

const locales = ['en', 'ru'];

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type Props = PropsWithChildren<{
  params: { locale: string };
}>;

export default function RootLayout({
  children, params
}: Props) {
  const isValidLocale = locales.some((cur) => cur === params.locale);
  if (!isValidLocale) notFound();

  return (
    <html lang="en" className="min-h-full flex flex-col">
      <body className={clsx(inter.className, 'flex flex-col grow')}>
        {children}
      </body>
    </html>
  )
}

